

/ as sysdba


-- 테이블 스페이스 생성
CREATE TABLESPACE TS_TEMPLETE DATAFILE 
  'D:\APP\DBF\TS_TEMPLETE.DBF' SIZE 4058M AUTOEXTEND ON NEXT 10M MAXSIZE 32767M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


-- 사용자 생성
-- DROP USER TEMPLETE ;
CREATE USER TEMPLETE IDENTIFIED BY TEMPLETE
DEFAULT  TABLESPACE TS_TEMPLETE
;


-- 권한부여
GRANT RESOURCE, CONNECT,CREATE TO TEMPLETE;




